1.python异常：
- 所有异常的基类：BaseException
- 异常分为 **系统内置异常** 和 **用户自定义异常**

2.系统内置异常：
- 主要分为 **Error** 和 **Warning** 两种
- 有些Error会返回错误码errno
- 时用时查，内置异常类层次如下：
```python
BaseException
 +-- SystemExit
 +-- KeyboardInterrupt
 +-- GeneratorExit
 +-- Exception
      +-- StopIteration
      +-- StopAsyncIteration
      +-- ArithmeticError
      |    +-- FloatingPointError
      |    +-- OverflowError
      |    +-- ZeroDivisionError
      +-- AssertionError
      +-- AttributeError
      +-- BufferError
      +-- EOFError
      +-- ImportError
      |    +-- ModuleNotFoundError
      +-- LookupError
      |    +-- IndexError
      |    +-- KeyError
      +-- MemoryError
      +-- NameError
      |    +-- UnboundLocalError
      +-- OSError
      |    +-- BlockingIOError
      |    +-- ChildProcessError
      |    +-- ConnectionError
      |    |    +-- BrokenPipeError
      |    |    +-- ConnectionAbortedError
      |    |    +-- ConnectionRefusedError
      |    |    +-- ConnectionResetError
      |    +-- FileExistsError
      |    +-- FileNotFoundError
      |    +-- InterruptedError
      |    +-- IsADirectoryError
      |    +-- NotADirectoryError
      |    +-- PermissionError
      |    +-- ProcessLookupError
      |    +-- TimeoutError
      +-- ReferenceError
      +-- RuntimeError
      |    +-- NotImplementedError
      |    +-- RecursionError
      +-- SyntaxError
      |    +-- IndentationError
      |         +-- TabError
      +-- SystemError
      +-- TypeError
      +-- ValueError
      |    +-- UnicodeError
      |         +-- UnicodeDecodeError
      |         +-- UnicodeEncodeError
      |         +-- UnicodeTranslateError
      +-- Warning
           +-- DeprecationWarning
           +-- PendingDeprecationWarning
           +-- RuntimeWarning
           +-- SyntaxWarning
           +-- UserWarning
           +-- FutureWarning
           +-- ImportWarning
           +-- UnicodeWarning
           +-- BytesWarning
           +-- ResourceWarning
```

3.自定义异常：
- 用户自定义异常均从派生于异常类Exception
- 建议自定义异常都以Exceptions或者except结尾，方便和内置异常区分

4.异常相关语法：
- 捕获异常：`try:...except(Exception1[, Exception2[,...ExceptionN]]]):...else:...`
    - try语句工作原理如下：
        - 首先，执行 try 子句 （try 和 except 关键字之间的（多行）语句）。
        - 如果没有异常发生，则跳过 except 子句 并完成 try 语句的执行。
        - 如果在执行try子句时发生了异常，则跳过该子句中剩下的部分。然后，如果异常的类型和except关键字后面的异常匹配，则执行except子句 ，然后继续执行try语句之后的代码。
        - 如果发生的异常和except子句中指定的异常不匹配，则将其传递到外部的try语句中；如果没有找到处理程序，则它是一个未处理异常，执行将停止并显示如上所示的消息。
```python
>>> while True:
...     try:
...         x = int(input("Please enter a number: "))
...         break
...     except ValueError as e:
...         print("Oops!  That was no valid number.  Try again...")
```
- 强制抛出异常raise
    - raise唯一的参数就是要抛出的异常。
    - 这个参数必须是一个异常实例或者是一个异常类(派生自Exception的类)
```python
>>> try:
...     raise NameError('HiThere')
... except NameError:
...     print('An exception flew by!')
...     raise
...
An exception flew by!
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
NameError: HiThere
```
- finally的使用
    - 如果存在finally子句，则finally子句将作为try语句结束前的最后一项任务被执行。finally子句不论try语句是否产生了异常都会被执行
    - 对于释放外部资源(例如文件或者网络连接)非常有用
```python
>>> def divide(x, y):
...     try:
...         result = x / y
...     except ZeroDivisionError:
...         print("division by zero!")
...     else:
...         print("result is", result)
...     finally:
...         print("executing finally clause")
```
